# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    # Finds CSC.exe and adds it to path for use in build step.    
    - name: Set up CSC.exe
      uses: yoavain/Setup-CSC@v5
    
    # Builds source into DLL.
    - name: Build DLL
      run: csc -target:library -out:%GITHUB_RUN_ID%_%GITHUB_RUN_NUMBER%_%GITHUB_SHA%.dll -reference:./lib/2019.3.6f1/UnityEngine.dll *.cs ./FileSystem/*.cs ./Collections/*.cs ./Collections/Generic/*.cs

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: "%GITHUB_RUN_ID%_%GITHUB_RUN_NUMBER%_%GITHUB_SHA%.dll"
        # Directory containing files to upload
        path: ./
